Test mapping of DatabaseAlreadyExists on postgres
prisma/quaint pull request #172
Opened 2020-08-27 14:23 UTC by tomhoule

2020-08-27 14:23 UTC, tomhoule commented on src/connector/postgres.rs
> +        // SET NAMES sets the client text encoding. It needs to be explicitly set for automatic
non-breaking space -> regular space

2020-08-27 15:18 UTC, pimeys requested changes

2020-08-27 15:18 UTC, pimeys commented on src/connector/postgres.rs
> +    #[tokio::test]
Could this be actually tested in the integration tests for all (or most) databases?

2020-08-27 15:23 UTC, pimeys commented on src/connector/postgres.rs
> +    #[tokio::test]
Meaning, in here https://github.com/prisma/quaint/blob/master/src/tests/query/error.rs

2021-07-05 05:44 UTC, tomhoule commented
This PR is stale, closing.

2021-07-05 05:44 UTC, closed without merging