Use connection-string
prisma/quaint pull request #202
Opened 2020-10-12 06:58 UTC by yoshuawuyts

Uses `connection-string` for JDBC parsing. This required mutable access to `properties`, so I've pushed `connection-string@0.1.5` which provides access to `properties_mut`.

Also I've made it so the JDBC parser handles errors in the string rather than silently continuing. This should make it easier to debug malformed strings (instead of a param not showing up, we'll return an error if we found one).

`connection-string` doesn't know how to _encode_ anything yet, so I haven't touched the ado.net logic. Hope this is good!

2020-10-12 07:14 UTC, yoshuawuyts commented
Oh, so in order for tests to pass I've had to rewrite the MSSQL connection string to always require the `jdbc:sqlserver` prefix. I'm assuming we weren't doing this because Prisma doesn't want to expose `jdbc:` to end-users. I get why we wouldn't want to expose that through Prisma; but should we be rewriting connection strings in quaint? I would assume the answer is "probably not", but keen to hear more.

2020-10-12 07:56 UTC, pimeys submitted a review, later dismissed

2020-10-12 08:03 UTC, pimeys requested changes
We should edit the docs in `single.rs` and `pooled.rs` to reflect the changes to the required connection string format. E.g. the added `jdbc:` prefix!

2020-10-27 07:14 UTC, pimeys commented
Closing in favor of https://github.com/prisma/quaint/pull/215/

2020-10-27 07:14 UTC, closed without merging