Expose maximum connection lifetimes
prisma/quaint pull request #267
Opened 2021-03-07 13:52 UTC by Sytten

This adds the `max_lifetime` on the builder and exposes `max_connection_lifetime` and `max_idle_connection_lifetime` via the URL parser.
Needed for serverless environments where it is not a good idea to never close connections, see https://github.com/prisma/prisma/issues/5977

2021-03-07 13:52 UTC, Sytten commented
Let me know if you want tests for that parsing somewhere

2021-03-10 09:46 UTC, pimeys commented
These are overwritten in https://github.com/prisma/prisma-engines/blob/master/query-engine/connectors/sql-query-connector/src/database/mssql.rs#L34-L35 et.al.

2021-03-10 12:51 UTC, Sytten commented
Yes will need to change that too.

2021-03-19 15:06 UTC, janpio approved these changes
Exposing these two options from our connection pool to potentially being able to use them from the Engines looks useful.

2021-03-23 21:16 UTC, Sytten commented
@pimeys @janpio I added some getters on the builder since I found this was the most straight forward way to not override the parameter in the engines. The url is parsed multiple times so it is quite confusing really (connection info in the engine, connection info in the builder and new method of the builder), but the builder getter wont lie.

2021-03-25 18:41 UTC, pimeys commented
Had a discussion with @Sytten and we decided that the defaults we set in the engines could be defined (and documented) in Quaint instead, removing the need for the getters.

2021-03-26 07:55 UTC, pimeys requested changes
Now you can try this out together with the engines by editing the topmost `Cargo.toml` in there and by adding

```toml
[patch."https://github.com/prisma/quaint"]
quaint = { path = "/path/to/local/quaint" } # this needs to be checked out to the correct branch
```

When you're happy how it works, we should merge them quite soon together due to otherwise somebody else might update quaint and get the changes beforehand, causing havoc in the worst case.

2021-03-26 07:55 UTC, pimeys commented on src/connector/postgres.rs
> +        let mut max_idle_connection_lifetime = None;
```suggestion
        let mut max_idle_connection_lifetime = Some(Duration::from_secs(300));
```

See: https://github.com/prisma/prisma-engines/blob/master/query-engine/connectors/sql-query-connector/src/database/postgresql.rs

2021-03-26 07:55 UTC, pimeys commented on src/connector/sqlite.rs
> +            let mut max_idle_connection_lifetime = None;
I think this is a good default for SQLite. See in https://github.com/prisma/prisma-engines/blob/master/query-engine/connectors/sql-query-connector/src/database/sqlite.rs#L51 we have a different value, but I'd remove it completely and let the default be infinite (SQLite doesn't hold a network connection anyhow).

2021-03-26 07:55 UTC, pimeys commented on src/connector/mysql.rs
> +        let mut max_idle_connection_lifetime = None;
```suggestion
        let mut max_idle_connection_lifetime = Some(Duration::from_secs(300));
```

And remove this in engines https://github.com/prisma/prisma-engines/blob/master/query-engine/connectors/sql-query-connector/src/database/mysql.rs

2021-03-26 07:55 UTC, pimeys commented on src/connector/mssql.rs
> +        let max_idle_connection_lifetime = props
Remember to remove this from the engines: https://github.com/prisma/prisma-engines/blob/master/query-engine/connectors/sql-query-connector/src/database/mssql.rs#L34

2021-03-26 07:57 UTC, pimeys commented on src/connector/mssql.rs
> +            .transpose()?;
```suggestion
            .transpose()?
            .unwrap_or_else(|| Some(Duration::from_secs(300)));
```

2021-04-06 15:18 UTC, pimeys approved these changes

2021-04-06 15:24 UTC, merged