Remove support for sqlite url prefix
prisma/quaint pull request #370
Opened 2022-06-01 10:51 UTC by pimeys

Merge only when Prisma 4 is due

Part of: https://github.com/prisma/prisma/issues/11468

2022-06-01 11:33 UTC, tomhoule approved these changes

2022-06-01 13:45 UTC, pimeys commented
> There is another case I think:
> 
> https://github.com/prisma/quaint/blob/8be4fab7f2f6213487b1d40f2d23a6de982a0cf6/src/single.rs#L134

I didn't save that file before committing...

2022-06-01 17:57 UTC, janpio requested changes
see comments

2022-06-02 10:02 UTC, janpio approved these changes

2022-06-08 08:25 UTC, merged