feat(PostgreSQL): support channel_binding query param
prisma/quaint pull request #424
Opened 2022-12-14 09:21 UTC by jannikkeye

This PR adds support for the channel_binding query parameter for PostgreSQL.

I've added two tests to check for correct parsing as well as falling back to the default value if none or invalid value is present.

2022-12-14 10:20 UTC, pimeys requested changes

2022-12-14 10:20 UTC, pimeys commented on src/connector/postgres.rs
> +                                message = "Unsupported Channel Binding channel_binding, defaulting to `prefer`",
```suggestion
                                message = "Unsupported Channel Binding {channel_binding}, defaulting to `prefer`",
```

2022-12-14 10:21 UTC, pimeys commented
a small nitpick, otherwise ready to go

2022-12-15 08:10 UTC, merged

2022-12-15 08:11 UTC, pimeys commented
thanks.

2022-12-15 12:51 UTC, pimeys commented
It needs testing and documentation. Which is not scheduled for the current sprint. Would you like to do it?

2022-12-15 12:51 UTC, pimeys commented
And quaint should be updated in the engines repo.

2022-12-19 06:05 UTC, jannikkeye commented
> It needs testing and documentation. Which is not scheduled for the current sprint. Would you like to do it?

Yeah, sure I’ll add the docs, I think I know where, have added a param before.